version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: volleyball-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: volleyball_db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    # 📝 NOTE: The healthcheck is no longer needed because we are using 'service_started' below.
    # I recommend keeping it in if you stick with the 'service_healthy' condition.

  app:
    build: .
    container_name: volleyball-stat-tracker
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/volleyball_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    env_file:
      - ./.env
    depends_on:
      db:
        # ✅ CHANGE: Using the simpler 'service_started' condition
        condition: service_started

volumes:
  postgres_data: