name: maven_docker_ci.yml

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows manual runs from the GitHub Actions UI
  workflow_dispatch:

jobs:
  build_test_push:
    name: Build, Test, and Push Docker Image
    runs-on: ubuntu-latest

    # *** NOTICE: The 'services: postgres:' block is completely removed! ***

    steps:
      # 1. SETUP AND CHECKOUT
      - name: 🔄 Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven # Cache Maven dependencies for faster builds

      # *** NOTICE: The 'Wait for PostgreSQL service to start' step is removed! ***

      # 2. BUILD AND TEST
      # This step now runs tests using the fast H2 in-memory database
      - name: Build and Run Tests
        run: mvn -B package -Dspring-boot.run.profiles=test --file pom.xml

      # 3. DOCKER BUILD AND PUSH (Continuous Delivery part)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # Use secrets for security
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Only push the image when merging/pushing to the master branch
          push: ${{ github.ref == 'refs/heads/master' }}
          # Use your correct Docker Hub username and image name
          tags: ${{ secrets.DOCKER_USERNAME }}/volleyball-stat-tracker:latest