name: maven_docker_ci.yml
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_test_push:
    name: Build, Test, and Push Docker Image
    runs-on: ubuntu-latest

    # CORRECT INDENTATION LEVEL FOR SERVICES
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: volleyball_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Ninjazach7!1
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    # CORRECT INDENTATION LEVEL FOR STEPS (Sibling of 'services')
    steps:
      - name: 🔄Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # ROBUST WAIT/DIAGNOSTICS STEP (Integrated Debugging on failure)
      - name: Wait for PostgreSQL service to start
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client
          echo "Waiting for Postgres on localhost:5432 (up to 60s)..."
          
          for i in {1..60}; do
            # Use -q for quiet, check the exit status
            pg_isready -h localhost -p 5432 -U postgres -d volleyball_db -q
            STATUS=$?
            echo "pg_isready status=$STATUS (attempt $i)"
          
            if [ $STATUS -eq 0 ]; then
              echo "PostgreSQL ready"
              exit 0
            fi
            sleep 1
          done
          
          # DIAGNOSTICS ON TIMEOUT FAILURE (60 seconds elapsed)
          echo "Postgres did not become ready in time" >&2
          echo "==== docker ps -a ===="
          docker ps -a --format "table {{.ID}}\t{{.Image}}\t{{.Names}}\t{{.Status}}"
          CONTAINER=$(docker ps -a --filter ancestor=postgres:13 --format '{{.ID}}' | head -n1)
          if [ -n "$CONTAINER" ]; then
            echo "==== docker logs (last 500 lines) for $CONTAINER ===="
            docker logs --tail 500 "$CONTAINER" || true
          else
            echo "No postgres container found"
          fi
          exit 1 # Fail the job

      # BUILD & TEST STEP
      - name: Build and Test JAR
        run: mvn -B package -Dspring-boot.run.profiles=test --file pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name:  Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/volleyball-stat-tracker
          tags: |
            type=sha,prefix=,suffix=,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      # DOCKER BUILD & PUSH STEP
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
