name: maven_docker_ci.yml
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_test_push:
    name: Build, Test, and Push Docker Image
    runs-on: ubuntu-latest

    # 🌟 NEW: Define the PostgreSQL service for integration tests
    services:
      postgres:
        image: postgres:13
        env:
          # CRUCIAL: These credentials MUST match your application.properties for CI
          POSTGRES_DB: volleyball_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Ninjazach7!1
        ports:
          - 5432:5432
        # Simple health check to ensure the container is ready
        options: >
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 🔄Checkout Code
        uses: actions/checkout@v4

      - name:  Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      #  NEW: Wait briefly for the database to fully initialize
      - name: Wait for PostgreSQL service to start
        run: sleep 5

      # 1. BUILD & TEST STEP (Now connects to the 'postgres' service)
      - name: Build and Test JAR
        # -Dspring-boot.run.profiles=test is kept to load application-test.properties if it exists
        run: mvn -B package -Dspring-boot.run.profiles=test --file pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name:  Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/volleyball-stat-tracker
          tags: |
            type=sha,prefix=,suffix=,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      # 2. DOCKER BUILD & PUSH STEP
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
